services:
  database:
    image: "postgres:16.0-alpine3.18"
    environment:
      # in environment: we cant pass configurations about the image that we are using, in this case, we are passing configurations for postgres image like user, password, database name
      POSTGRES_PASSWORD: "123456"
      # first parameter: host, second parameter: guest
    ports:
      - "5432:5432"

  # mailcatcher:
  # - "host-guest(container))"
